---
title: "General figures"
author: "Christian Diener"
output:
    html_notebook: default
    html_document:
        toc: true
        toc_float: true
---

# Clinical data

```{r}
library(mbtools)
library(ggplot2)

theme_set(theme_bw())
status_map <- c("normal", "IFG", "IGT", "IFG+ITG", "T2D", "T2D treated")

ps <- readRDS("../data/taxonomy_clean.rds")
meta <- as.data.table(as(sample_data(ps), "data.frame"))
meta[, diabetes_status := factor(status_map[diabetes_status], levels=status_map)]
```

Correlations between clinical variables:

```{r}
library(pheatmap)
corrs <- cor(meta[, sapply(meta, is.numeric), with=F], method="spearman", use="pairwise.complete.obs")

colors <- colorRampPalette(rev(RColorBrewer::brewer.pal(n = 7, name = "RdBu")))(128)
pheatmap(corrs, col=colors, border_color=NA, filename="cors.png", fontsize=3,
         width=10, height=10)
```

BMI vs diabetes_status:

```{r}
pl <- ggplot(meta, aes(x=diabetes_status, y=bmi, col=diabetes_status)) + geom_jitter(width=0.3) + 
  geom_smooth(method="glm", aes(group=0, x=as.numeric(diabetes_status))) +
  guides(color=FALSE) + labs(x="", y="BMI")
ggsave("status_vs_bmi.svg")
pl
```

BMI vs. glucose AUC:

```{r}
pl <- ggplot(meta, aes(x=bmi, y=auc_glucose, col=diabetes_status)) + geom_point() + 
  geom_smooth(method="glm", aes(group=0)) + scale_y_log10(breaks=c(5000, 10000, 20000, 50000)) +
  guides(color=FALSE) + labs(x="BMI", y="area under glucose curve")
ggsave("auc_vs_bmi.svg")
pl
```

Visceral fat vs area under glucose curve:

```{r}
pl <- ggplot(meta, aes(x=visceral_fat, y=auc_glucose, col=diabetes_status)) + geom_point(alpha=0.5) + 
  geom_smooth(method="glm", aes(group=0)) + scale_y_log10(breaks=c(5000, 10000, 20000, 50000)) +
  guides(color=FALSE) + labs(x="visceral fat [%]", y="area under glucose curve")
ggsave("fat_vs_auc.svg")
pl
```


Correlations:

```{r}
print(cor.test(~ as.numeric(diabetes_status) + bmi, data=meta, method="spearman"))
print(cor.test(~ auc_glucose + bmi, data=meta, method="spearman"))
print(cor.test(~ auc_glucose + visceral_fat, data=meta, method="spearman"))
```



Glucose and insulin curves:

```{r}
status_map <- c("normal", "IFG", "IGT", "IFG+ITG", "T2D", "T2D treated")

cols <- c(paste0("glucose_", seq(0, 121, 30)), "id", "diabetes_status")
glc <- meta[ , ..cols]
glc <- melt(glc, c("id", "diabetes_status"), variable.name="time",
            value.name="glucose")
glc[, time := as.numeric(tstrsplit(time, "_")[[2]])]

pl <- ggplot(glc, aes(x=time, y=glucose, col=diabetes_status, group=id)) +
      geom_line(alpha=0.25, lwd=1) + guides(colour = guide_legend(override.aes = list(alpha = 1))) +
      labs(color="", x="time [min]", y="blood glucose [mg/dL]") + scale_color_hue(direction=-1)
ggsave("glucose_curves.svg", pl)
pl
```

```{r}
cols <- c(paste0("insulin_", seq(0, 121, 30)), "id", "beta_cell_function")
ins <- meta[ , ..cols]
ins <- melt(ins, c("id", "beta_cell_function"), variable.name="time",
            value.name="insulin")
ins[, time := as.numeric(tstrsplit(time, "_")[[2]])]

pl <- ggplot(ins, aes(x=time, y=insulin, col=beta_cell_function, group=id)) +
      geom_line(alpha=0.5, lwd=0.5) +
      labs(color="", x="time [min]", y="insulin [mg/dL]") + viridis::scale_color_viridis()
ggsave("insuline_curves.svg")
pl

```

## Microbiome data

Ordination:

```{r}
sdata <- as.data.frame(meta)
rownames(sdata) <- sample_names(ps)
sample_data(ps) <- sdata
ord <- ordinate(ps, method="PCoA")
plot_ordination(ps, ord, color="diabetes_status", shape = "metformin")
ggsave("ordination.svg")
```

Family distribution:

```{r, fig.width=12, fig.height=4}
pl <- plot_taxa(ps)
ggsave("phylum_bars.png", width=12, height=4, dpi=200)
pl
```

PERMANOVA:

```{r}
perm <- readRDS("../data/permanova.rds")

# Explained variance
r2s <- perm$aov.tab
sum(r2s[r2s[, 6] < 0.05, 5], na.rm=T)
sum(r2s[r2s[, 6] < 0.1, 5], na.rm=T)
```



